export interface Treatment {
  id: string;
  name: string;
  description: string;
  icon: string;
  slug: string;
  image: string;
  shortDescription?: string;
}

export const allTreatments: Treatment[] = [
  {
    id: 'skin-disease',
    name: 'Skin Disease Treatment',
    description: 'Comprehensive homeopathic treatment for various skin diseases',
    icon: '🩹',
    slug: 'skin-disease',
    image: '/images/services/skin-disease.png',
    shortDescription: 'Natural treatment for skin conditions',
  },
  {
    id: 'hair-loss',
    name: 'Hair Loss Treatment',
    description: 'Effective solutions for hair fall, alopecia, and hair growth restoration',
    icon: '💇',
    slug: 'hair-loss',
    image: '/images/services/hair-loss.png',
    shortDescription: 'Restore your hair naturally',
  },
  {
    id: 'allergy',
    name: 'Allergy Treatment',
    description: 'Treatment for allergic reactions and immune system disorders',
    icon: '🤧',
    slug: 'allergy',
    image: '/images/services/allergy.png',
    shortDescription: 'Overcome allergies naturally',
  },
  {
    id: 'weight-loss-diet',
    name: 'Weight Loss Diet Counseling',
    description: 'Personalized diet plans and counseling for healthy weight management',
    icon: '⚖️',
    slug: 'weight-loss-diet',
    image: '/images/services/weight-loss-diet.png',
    shortDescription: 'Achieve healthy weight naturally',
  },
  {
    id: 'ibs',
    name: 'Irritable Bowel Syndrome (IBS) Treatment',
    description: 'Natural homeopathic treatment for IBS and digestive disorders',
    icon: '🫔',
    slug: 'ibs',
    image: '/images/services/ibs.png',
    shortDescription: 'Relief from IBS symptoms',
  },
  {
    id: 'gastritis',
    name: 'Gastritis Treatment',
    description: 'Effective homeopathic remedies for gastritis and stomach inflammation',
    icon: '🫔',
    slug: 'gastritis',
    image: '/images/services/gastritis.png',
    shortDescription: 'Treat gastritis naturally',
  },
  {
    id: 'hypertension',
    name: 'Hypertension Treatment',
    description: 'Natural treatment for high blood pressure management',
    icon: '❤️',
    slug: 'hypertension',
    image: '/images/services/hypertension.png',
    shortDescription: 'Control blood pressure naturally',
  },
  {
    id: 'kidney-stone',
    name: 'Kidney Stone Treatment',
    description: 'Homeopathic treatment for kidney stones and urinary disorders',
    icon: '🪨',
    slug: 'kidney-stone',
    image: '/images/services/kidney-stone.png',
    shortDescription: 'Natural kidney stone relief',
  },
  {
    id: 'gall-bladder-stone',
    name: 'Gall Bladder (Biliary) Stone Treatment',
    description: 'Natural homeopathic solutions for gallbladder stones',
    icon: '🪨',
    slug: 'gall-bladder-stone',
    image: '/images/services/gall-bladder-stone.png',
    shortDescription: 'Gallbladder stone treatment',
  },
  {
    id: 'cancer',
    name: 'Cancer Treatment',
    description: 'Supportive homeopathic care for cancer patients',
    icon: '🏥',
    slug: 'cancer',
    image: '/images/services/cancer.png',
    shortDescription: 'Supportive cancer care',
  },
  {
    id: 'liver-disease',
    name: 'Liver Disease Treatment',
    description: 'Comprehensive homeopathic treatment for liver disorders',
    icon: '🏥',
    slug: 'liver-disease',
    image: '/images/services/liver-disease.png',
    shortDescription: 'Liver health restoration',
  },
  {
    id: 'arthritis',
    name: 'Arthritis Management',
    description: 'Effective homeopathic treatment for arthritis and joint pain',
    icon: '🦴',
    slug: 'arthritis',
    image: '/images/services/arthritis.png',
    shortDescription: 'Manage arthritis naturally',
  },
  {
    id: 'dandruff',
    name: 'Dandruff Treatment',
    description: 'Natural remedies for dandruff and scalp conditions',
    icon: '💆',
    slug: 'dandruff',
    image: '/images/services/dandruff.png',
    shortDescription: 'Get rid of dandruff naturally',
  },
  {
    id: 'diabetes',
    name: 'Diabetes Management',
    description: 'Holistic homeopathic approach to diabetes management',
    icon: '💉',
    slug: 'diabetes',
    image: '/images/services/diabetes.png',
    shortDescription: 'Natural diabetes management',
  },
  {
    id: 'obesity',
    name: 'Obesity Treatment',
    description: 'Comprehensive weight management and obesity treatment',
    icon: '⚖️',
    slug: 'obesity',
    image: '/images/services/obesity.png',
    shortDescription: 'Obesity treatment program',
  },
  {
    id: 'bronchial-asthma',
    name: 'Bronchial Asthma Treatment',
    description: 'Natural homeopathic treatment for asthma and respiratory issues',
    icon: '🫁',
    slug: 'bronchial-asthma',
    image: '/images/services/bronchial-asthma.png',
    shortDescription: 'Treat asthma naturally',
  },
  {
    id: 'infertility',
    name: 'Infertility Evaluation / Treatment',
    description: 'Comprehensive homeopathic treatment for male and female infertility',
    icon: '👶',
    slug: 'infertility',
    image: '/images/services/infertility.png',
    shortDescription: 'Achieve natural conception',
  },
  {
    id: 'acne',
    name: 'Acne / Pimples Treatment',
    description: 'Effective homeopathic solutions for acne and pimples',
    icon: '✨',
    slug: 'acne',
    image: '/images/services/acne.png',
    shortDescription: 'Clear skin naturally',
  },
  {
    id: 'bronchitis',
    name: 'Bronchitis Treatment',
    description: 'Natural treatment for acute and chronic bronchitis',
    icon: '🫁',
    slug: 'bronchitis',
    image: '/images/services/bronchitis.png',
    shortDescription: 'Treat bronchitis naturally',
  },
  {
    id: 'cervical-spondylitis',
    name: 'Cervical Spondylitis Treatment',
    description: 'Effective homeopathic care for cervical spine issues',
    icon: '🦴',
    slug: 'cervical-spondylitis',
    image: '/images/services/cervical-spondylitis.png',
    shortDescription: 'Cervical spondylitis relief',
  },
  {
    id: 'cysts',
    name: 'Cysts Treatment',
    description: 'Homeopathic treatment for various types of cysts',
    icon: '🏥',
    slug: 'cysts',
    image: '/images/services/cysts.png',
    shortDescription: 'Cyst treatment naturally',
  },
  {
    id: 'depression',
    name: 'Depression Treatment',
    description: 'Holistic homeopathic care for depression and emotional wellbeing',
    icon: '🧠',
    slug: 'depression',
    image: '/images/services/depression.png',
    shortDescription: 'Natural depression relief',
  },
  {
    id: 'dermatitis',
    name: 'Dermatitis Treatment',
    description: 'Effective homeopathic solutions for dermatitis and skin inflammation',
    icon: '🩹',
    slug: 'dermatitis',
    image: '/images/services/dermatitis.png',
    shortDescription: 'Treat dermatitis naturally',
  },
  {
    id: 'eczema',
    name: 'Eczema Treatment',
    description: 'Natural remedies for eczema and chronic skin conditions',
    icon: '🩹',
    slug: 'eczema',
    image: '/images/services/eczema.png',
    shortDescription: 'Eczema relief naturally',
  },
  {
    id: 'insomnia',
    name: 'Insomnia Treatment',
    description: 'Homeopathic solutions for sleep disorders and insomnia',
    icon: '😴',
    slug: 'insomnia',
    image: '/images/services/insomnia.png',
    shortDescription: 'Sleep better naturally',
  },
  {
    id: 'dysmenorrhea',
    name: 'Dysmenorrhea Treatment',
    description: 'Natural treatment for painful periods and menstrual disorders',
    icon: '👩‍⚕️',
    slug: 'dysmenorrhea',
    image: '/images/services/dysmenorrhea.png',
    shortDescription: 'Menstrual pain relief',
  },
  {
    id: 'migraine',
    name: 'Migraine Treatment',
    description: 'Effective homeopathic care for migraines and headaches',
    icon: '🤕',
    slug: 'migraine',
    image: '/images/services/migraine.png',
    shortDescription: 'Migraine relief naturally',
  },
  {
    id: 'thyroid',
    name: 'Thyroid Disorder Treatment',
    description: 'Comprehensive homeopathic treatment for thyroid disorders',
    icon: '🏥',
    slug: 'thyroid',
    image: '/images/services/thyroid.png',
    shortDescription: 'Thyroid health restoration',
  },
  {
    id: 'psoriasis',
    name: 'Psoriasis Treatment',
    description: 'Natural homeopathic solutions for psoriasis and skin disorders',
    icon: '🩹',
    slug: 'psoriasis',
    image: '/images/services/psoriasis.png',
    shortDescription: 'Psoriasis treatment naturally',
  },
  {
    id: 'rheumatism',
    name: 'Rheumatism Treatment',
    description: 'Effective treatment for rheumatism and rheumatoid conditions',
    icon: '🦴',
    slug: 'rheumatism',
    image: '/images/services/rheumatism.png',
    shortDescription: 'Rheumatism relief naturally',
  },
  {
    id: 'dengue',
    name: 'Dengue Fever Treatment',
    description: 'Supportive homeopathic care for dengue fever',
    icon: '🏥',
    slug: 'dengue',
    image: '/images/services/dengue.png',
    shortDescription: 'Dengue fever support',
  },
  {
    id: 'heart-conditions',
    name: 'Heart Conditions',
    description: 'Supportive homeopathic care for various heart conditions',
    icon: '❤️',
    slug: 'heart-conditions',
    image: '/images/services/heart-conditions.png',
    shortDescription: 'Heart health support',
  },
  {
    id: 'skin-disorder',
    name: 'Skin Disorder',
    description: 'Comprehensive treatment for various skin disorders',
    icon: '🩹',
    slug: 'skin-disorder',
    image: '/images/services/skin-disorder.png',
    shortDescription: 'Skin disorder treatment',
  },
  {
    id: 'psychological-problems',
    name: 'Psychological Problems Adult Counselling',
    description: 'Professional counseling and homeopathic care for adult psychological issues',
    icon: '🧠',
    slug: 'psychological-problems',
    image: '/images/services/psychological-problems.png',
    shortDescription: 'Adult psychological counseling',
  },
  {
    id: 'neurological-problems',
    name: 'Neurological Problems',
    description: 'Comprehensive treatment for various neurological disorders',
    icon: '🧠',
    slug: 'neurological-problems',
    image: '/images/services/neurological-problems.png',
    shortDescription: 'Neurological disorder treatment',
  },
  {
    id: 'youth-counselling',
    name: 'Youth Counselling',
    description: 'Professional counseling for youth and adolescents',
    icon: '👨‍🎓',
    slug: 'youth-counselling',
    image: '/images/services/youth-counselling.png',
    shortDescription: 'Youth counseling services',
  },
  {
    id: 'joints-musculoskeletal',
    name: 'Joints and Musculoskeletal Disorders',
    description: 'Effective treatment for joint and musculoskeletal problems',
    icon: '🦴',
    slug: 'joints-musculoskeletal',
    image: '/images/services/joints-musculoskeletal.png',
    shortDescription: 'Joint health restoration',
  },
  {
    id: 'lifestyle-disorders',
    name: 'Lifestyle Disorders Treatment',
    description: 'Holistic approach to managing lifestyle-related disorders',
    icon: '🏥',
    slug: 'lifestyle-disorders',
    image: '/images/services/lifestyle-disorders.png',
    shortDescription: 'Lifestyle disorder management',
  },
  {
    id: 'acute-chronic-diseases',
    name: 'Acute and Chronic Diseases',
    description: 'Comprehensive homeopathic treatment for acute and chronic conditions',
    icon: '🏥',
    slug: 'acute-chronic-diseases',
    image: '/images/services/acute-chronic-diseases.png',
    shortDescription: 'Acute and chronic disease care',
  },
  {
    id: 'pcod',
    name: 'PCOD Treatment',
    description: 'Natural homeopathic solutions for hormonal balance and ovarian health',
    icon: '⚖️',
    slug: 'pcod',
    image: '/images/services/pcod.png',
    shortDescription: 'PCOD management naturally',
  },
  {
    id: 'mental-health',
    name: 'Mental Health & Counseling',
    description: 'Holistic care for emotional wellbeing and psychological health',
    icon: '🧠',
    slug: 'mental-health',
    image: '/images/services/mental-health.png',
    shortDescription: 'Mental health support',
  },
  {
    id: 'allergies',
    name: 'Allergies & Immunology',
    description: 'Treatment for allergic reactions, asthma, and immune system disorders',
    icon: '🤧',
    slug: 'allergies',
    image: '/images/services/allergies.png',
    shortDescription: 'Allergy and immunity support',
  },
];

export function getTreatmentBySlug(slug: string): Treatment | undefined {
  return allTreatments.find(t => t.slug === slug);
}

export function searchTreatments(query: string): Treatment[] {
  const lowercaseQuery = query.toLowerCase();
  return allTreatments.filter(t =>
    t.name.toLowerCase().includes(lowercaseQuery) ||
    t.description.toLowerCase().includes(lowercaseQuery)
  );
}